# vim: set syntax=helm:

{{- $fullname := include "ckan.fullname" . -}}

{{- $sessionEncryptKeySecret := lookup "v1" "Secret" .Release.Namespace .Values.config.session.encryptKey.secretName }}
{{- $sessionEncryptKey := "" }}
{{- if $sessionEncryptKeySecret }}
  {{- $sessionEncryptKey = (get $sessionEncryptKeySecret "data").key | b64dec }}
{{- end }}{{/* sessionEncryptKeySecret */}}

{{- $sessionValidateKeySecret := lookup "v1" "Secret" .Release.Namespace .Values.config.session.validateKey.secretName }}
{{- $sessionValidateKey := "" }}
{{- if $sessionValidateKeySecret }}
  {{- $sessionValidateKey = (get $sessionValidateKeySecret "data").key | b64dec }}
{{- end }}{{/* sessionValidateKeySecret */}}

{{- $csrfSecretKeySecret := lookup "v1" "Secret" .Release.Namespace .Values.config.csrfProtection.secret.secretName }}
{{- $csrfSecretKey := "" }}
{{- if $csrfSecretKeySecret }}
  {{- $csrfSecretKey = (get $csrfSecretKeySecret "data").key | b64dec }}
{{- end }}{{/* $csrfSecretKeySecret */}}

{{- $databasePasswordSecret := lookup "v1" "Secret" .Release.Namespace .Values.config.database.password.secretName }}
{{- $databasePassword := "" }}
{{- if $databasePasswordSecret }}
  {{- $databasePassword = (get $databasePasswordSecret "data").password | b64dec }}
{{- end }}{{/* databasePasswordSecret */}}
{{- $databaseUser := .Values.config.database.username }}
{{- $databaseHost := .Values.config.database.host }}
{{- $databasePort := .Values.config.database.port | int }}
{{- $databaseName := .Values.config.database.dbname }}

{{- $smtpSecret := lookup "v1" "Secret" .Release.Namespace .Values.config.mail.smtp.secretName }}
{{- $smtpServer := "" }}
{{- $smtpUser := "" }}
{{- $smtpPassword := "" }}
{{- if $smtpSecret }}
  {{- $smtpServer = (get $smtpSecret "data").server | b64dec }}
  {{- $smtpUser = (get $smtpSecret "data").user | b64dec }}
  {{- $smtpPassword = (get $smtpSecret "data").password | b64dec }}
{{- end }}{{/* if $smtpSecret */}}

{{- $pluginsEnabled := concat .Values.config.extensionPluginsEnabled .Values.config.basicPluginsEnabled }}

---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ $fullname }}-config-generated
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
stringData:
  10-plugins.ini: |-
    ckan.plugins={{ $pluginsEnabled | join " " }} 
  10-session.ini: |-
    beaker.session.secret={{ $sessionEncryptKey | trim }}
    beaker.session.validate_key={{ $sessionValidateKey | trim }}
  20-csrf.ini: |-
    WTF_CSRF_SECRET_KEY={{ $csrfSecretKey | trim }}

# see https://docs.ckan.org/en/2.10/maintaining/configuration.html#environment-variables
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-env-generated
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
stringData:
  CKAN_SQLALCHEMY_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" $databaseUser $databasePassword $databaseHost $databasePort $databaseName }}
  CKAN_SITE_URL: {{ .Values.config.url }}
  CKAN_REDIS_URL: {{ .Values.config.redis.url }}
  CKAN_SOLR_URL: {{ .Values.config.solr.url }}
  CKAN_SMTP_SERVER: {{ $smtpServer | trim }}
  CKAN_SMTP_STARTTLS: "true"
  CKAN_SMTP_USER: {{ $smtpUser | trim }}
  CKAN_SMTP_PASSWORD: {{ $smtpPassword | trim | quote }}
  CKAN_SMTP_MAIL_FROM: {{ .Values.config.mail.from | trim }}
