apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckan.fullname" . }}-ckan
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ckan.selectorLabels" . | nindent 4 }}
